env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  semi: error
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  no-unused-vars:
    - warn
    